import './mapping.css';
import { DataRow, exportCsv, exportXlsx, getColumns, parseFile, SAMPLE_ROWS } from './data';
import { applyColumnMappings, ColumnMapping, validateMappings } from './mapping';

const state = { sourceName:'샘플 데이터', original:SAMPLE_ROWS.map((r)=>({...r})), rows:SAMPLE_ROWS.map((r)=>({...r})), mappings:[] as ColumnMapping[] };
const byId=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const el={file:byId<HTMLInputElement>('mappingFile'),source:byId<HTMLElement>('mappingSource'),sourceColumn:byId<HTMLSelectElement>('mappingSourceColumn'),target:byId<HTMLInputElement>('mappingTargetColumn'),list:byId<HTMLElement>('mappingList'),status:byId<HTMLElement>('mappingStatus'),meta:byId<HTMLElement>('mappingMeta'),head:byId<HTMLTableSectionElement>('mappingHead'),body:byId<HTMLTableSectionElement>('mappingBody')};
function clone(rows:DataRow[]){return rows.map((r)=>({...r}));}
function setStatus(message:string,error=false){el.status.textContent=message;el.status.dataset.error=error?'true':'false';}
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),0);}
function render(){
  const columns=getColumns(state.rows); el.source.textContent=`${state.sourceName} · ${state.rows.length}행`; el.meta.textContent=`${state.rows.length} rows · ${columns.length} columns`;
  const selected=el.sourceColumn.value; el.sourceColumn.replaceChildren(...columns.map((c)=>{const o=document.createElement('option');o.value=c;o.textContent=c;return o;})); if(columns.includes(selected))el.sourceColumn.value=selected;
  if(!state.mappings.length){const p=document.createElement('p');p.className='empty';p.textContent='아직 매핑 규칙이 없습니다.';el.list.replaceChildren(p);}else{const f=document.createDocumentFragment();state.mappings.forEach((m,i)=>{const row=document.createElement('div');row.className='mapping-rule';const s=document.createElement('span');s.textContent=`${m.source} → ${m.target}`;const b=document.createElement('button');b.textContent='삭제';b.onclick=()=>{state.mappings.splice(i,1);render();};row.append(s,b);f.append(row);});el.list.replaceChildren(f);}
  const hr=document.createElement('tr');columns.forEach(c=>{const th=document.createElement('th');th.textContent=c;hr.appendChild(th);});el.head.replaceChildren(hr);
  const frag=document.createDocumentFragment();state.rows.slice(0,50).forEach(r=>{const tr=document.createElement('tr');columns.forEach(c=>{const td=document.createElement('td');td.textContent=r[c]==null?'':String(r[c]);tr.appendChild(td);});frag.appendChild(tr);});el.body.replaceChildren(frag);
}
function addMapping(){const source=el.sourceColumn.value,target=el.target.value.trim();if(!source||!target){setStatus('원본 컬럼과 표준 컬럼명을 입력하세요.',true);return;}const next=[...state.mappings,{source,target}];const errors=validateMappings(getColumns(state.rows),next);if(errors.length){setStatus(errors[0]!,true);return;}state.mappings=next;el.target.value='';render();setStatus('매핑 규칙을 추가했습니다.');}
function apply(){if(!state.mappings.length){setStatus('적용할 매핑이 없습니다.',true);return;}try{state.rows=applyColumnMappings(state.rows,state.mappings);state.mappings=[];render();setStatus('컬럼 매핑을 적용했습니다.');}catch(e){setStatus(e instanceof Error?e.message:'매핑에 실패했습니다.',true);}}
async function loadFile(){const file=el.file.files?.[0];if(!file)return;try{const rows=await parseFile(file);state.sourceName=file.name;state.original=clone(rows);state.rows=clone(rows);state.mappings=[];render();setStatus('파일을 불러왔습니다.');}catch(e){setStatus(e instanceof Error?e.message:'파일을 읽지 못했습니다.',true);}finally{el.file.value='';}}
el.file.onchange=()=>void loadFile();byId<HTMLButtonElement>('mappingSample').onclick=()=>{state.sourceName='샘플 데이터';state.original=clone(SAMPLE_ROWS);state.rows=clone(SAMPLE_ROWS);state.mappings=[];render();};byId<HTMLButtonElement>('mappingAdd').onclick=addMapping;byId<HTMLButtonElement>('mappingApply').onclick=apply;byId<HTMLButtonElement>('mappingReset').onclick=()=>{state.rows=clone(state.original);state.mappings=[];render();setStatus('원본으로 복원했습니다.');};byId<HTMLButtonElement>('mappingCsv').onclick=()=>download(exportCsv(state.rows),'mapped-data.csv');byId<HTMLButtonElement>('mappingXlsx').onclick=()=>download(exportXlsx(state.rows),'mapped-data.xlsx');render();setStatus('원본 컬럼을 선택하고 표준 컬럼명을 지정하세요.');
