import './mapping.css';
import { DataRow, exportCsv, exportXlsx, getColumns, parseFile, SAMPLE_ROWS } from './data';
import { applyColumnMappings, ColumnMapping, validateMappings } from './mapping';

const state = { sourceName:'샘플 데이터', original:SAMPLE_ROWS.map((r)=>({...r})), rows:SAMPLE_ROWS.map((r)=>({...r})), mappings:[] as ColumnMapping[] };
const byId=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const el={file:byId<HTMLInputElement>('mappingFile'),source:byId<HTMLElement>('mappingSource'),sourceColumn:byId<HTMLSelectElement>('mappingSourceColumn'),target:byId<HTMLInputElement>('mappingTargetColumn'),list:byId<HTMLElement>('mappingList'),status:byId<HTMLElement>('mappingStatus'),meta:byId<HTMLElement>('mappingMeta'),head:byId<HTMLTableSectionElement>('mappingHead'),body:byId<HTMLTableSectionElement>('mappingBody')};
function clone(rows:DataRow[]){return rows.map((r)=>({...r}));}
function setStatus(message:string,error=false){el.status.textContent=message;el.status.dataset.error=error?'true':'false';}
function friendlyError(error:unknown){const raw=error instanceof Error?error.message:String(error);return raw.replaceAll('컬럼','항목').replaceAll('매핑','이름 변경').replaceAll('source','원본 항목').replaceAll('target','새 항목').trim()||'항목 이름을 바꾸지 못했습니다. 입력값을 확인해 주세요.';}
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),0);}
function render(){
  const columns=getColumns(state.rows); el.source.textContent=`${state.sourceName} · ${state.rows.length}행`; el.meta.textContent=`${state.rows.length}행 · ${columns.length}개 항목`;
  const selected=el.sourceColumn.value; el.sourceColumn.replaceChildren(...columns.map((c)=>{const o=document.createElement('option');o.value=c;o.textContent=c;return o;})); if(columns.includes(selected))el.sourceColumn.value=selected;
  if(!state.mappings.length){const p=document.createElement('p');p.className='empty';p.textContent='아직 바꿀 항목 이름을 추가하지 않았습니다.';el.list.replaceChildren(p);}else{const f=document.createDocumentFragment();state.mappings.forEach((m,i)=>{const row=document.createElement('div');row.className='mapping-rule';const s=document.createElement('span');s.textContent=`${m.source} → ${m.target}`;const b=document.createElement('button');b.textContent='삭제';b.onclick=()=>{state.mappings.splice(i,1);render();};row.append(s,b);f.append(row);});el.list.replaceChildren(f);}
  const hr=document.createElement('tr');columns.forEach(c=>{const th=document.createElement('th');th.textContent=c;hr.appendChild(th);});el.head.replaceChildren(hr);
  const frag=document.createDocumentFragment();state.rows.slice(0,50).forEach(r=>{const tr=document.createElement('tr');columns.forEach(c=>{const td=document.createElement('td');td.textContent=r[c]==null?'':String(r[c]);tr.appendChild(td);});frag.appendChild(tr);});el.body.replaceChildren(frag);
}
function addMapping(){const source=el.sourceColumn.value,target=el.target.value.trim();if(!source||!target){setStatus('바꿀 원본 항목과 새 항목 이름을 모두 입력해 주세요.',true);return;}const next=[...state.mappings,{source,target}];const errors=validateMappings(getColumns(state.rows),next);if(errors.length){setStatus(friendlyError(errors[0]!),true);return;}state.mappings=next;el.target.value='';render();setStatus('이름 변경을 추가했습니다.');}
function apply(){if(!state.mappings.length){setStatus('먼저 바꿀 항목 이름을 추가해 주세요.',true);return;}try{state.rows=applyColumnMappings(state.rows,state.mappings);state.mappings=[];render();setStatus('항목 이름을 바꿨습니다.');}catch(e){setStatus(friendlyError(e),true);}}
async function loadFile(){const file=el.file.files?.[0];if(!file)return;try{const rows=await parseFile(file);state.sourceName=file.name;state.original=clone(rows);state.rows=clone(rows);state.mappings=[];render();setStatus('파일을 불러왔습니다.');}catch(e){setStatus(friendlyError(e),true);}finally{el.file.value='';}}
el.file.onchange=()=>void loadFile();byId<HTMLButtonElement>('mappingSample').onclick=()=>{state.sourceName='샘플 데이터';state.original=clone(SAMPLE_ROWS);state.rows=clone(SAMPLE_ROWS);state.mappings=[];render();setStatus('샘플 파일을 열었습니다. 바꿀 항목 이름을 정해 보세요.');};byId<HTMLButtonElement>('mappingAdd').onclick=addMapping;byId<HTMLButtonElement>('mappingApply').onclick=apply;byId<HTMLButtonElement>('mappingReset').onclick=()=>{state.rows=clone(state.original);state.mappings=[];render();setStatus('처음 불러온 상태로 되돌렸습니다.');};byId<HTMLButtonElement>('mappingCsv').onclick=()=>download(exportCsv(state.rows),'항목이름-변경결과.csv');byId<HTMLButtonElement>('mappingXlsx').onclick=()=>download(exportXlsx(state.rows),'항목이름-변경결과.xlsx');render();setStatus('원본 항목을 선택하고 새 이름을 입력하세요.');
